apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/duduio2050/k8s
    targetRevision: main
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true